modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "LGPL-3.0"

[[mods]]
modId = "fixsoundseed"
version = "${version}"
displayName = "FixSoundSeed"
authors = "KabanFriends"
description = '''
Fixes MC-253055
'''
#logoFile = ""

[[dependencies.fixsoundseed]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fixsoundseed]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
